-- BRASA 35 - estrutura inicial para Supabase
create table if not exists categories (
 id bigint generated by default as identity primary key,
 name text not null unique,
 position int not null default 0,
 active boolean not null default true,
 created_at timestamptz default now()
);
create table if not exists products (
 id bigint generated by default as identity primary key,
 name text not null,
 category_id bigint references categories(id),
 price numeric(10,2) not null default 0,
 tag text,
 description text,
 image_url text,
 allow_extras boolean not null default false,
 available boolean not null default true,
 paused_until timestamptz,
 position int not null default 0,
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);
create table if not exists store_settings (
 id int primary key default 1 check (id=1),
 store_name text not null default 'BRASA 35',
 whatsapp text,
 pix_key text,
 instagram text,
 address text,
 minimum_order numeric(10,2) default 0,
 delivery_fee numeric(10,2) default 0,
 store_open boolean default true,
 paused_until timestamptz,
 updated_at timestamptz default now()
);
insert into store_settings(id,store_name,whatsapp,pix_key,instagram,address)
values(1,'BRASA 35','62998230185','705.698.571-80','@gfgtech14','Setor Aeroporto, Goiânia - GO')
on conflict(id) do nothing;

alter table categories enable row level security;
alter table products enable row level security;
alter table store_settings enable row level security;

create policy "public read categories" on categories for select using (active=true);
create policy "public read products" on products for select using (true);
create policy "public read settings" on store_settings for select using (true);

-- Escrita somente para usuários autenticados do painel.
create policy "admin categories" on categories for all to authenticated using (true) with check (true);
create policy "admin products" on products for all to authenticated using (true) with check (true);
create policy "admin settings" on store_settings for all to authenticated using (true) with check (true);
